### ISSUE TITLE
token_missing_here() command

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#103]
would detect, if we  (still) need to put token there.

Would be useful when there are sevear robot starting points.

analogy to  "token_here()"

**Comment by aroberge** [comment]
Currently, other than for `at_goal()`, there is a consistent choice that has been made to **not** have goal-related tests.  Thus, there is no `wall_missing_here()`, `object_missing_here()` [which would return the type of object missing], `token_missing_here()` [as you point out].   

**Initial** starting position, orientation, and the number of tokens at a grid point can take arbitrary values.
**Final** values are unique *except* that the final position might be one of several possibility.  However, the number of tokens required at a given location is unique, and known before the programs starts. The different behaviour for the final position (one of many possible choices) makes the test `at_goal()` required. 

I'd prefer to keep it that way (no tests for final configuration, other than final position through `at_goal()` since the final position is the only possible unknown value of the final configuration when a world is set up) for consistency.

This brings me to mention another issue that I am about to enter, suggesting the removal of `at_goal_orientation()` which breaks the above-mentioned pattern.
