### ISSUE TITLE
integrate verify() option in world goals editor

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#107]
Could there be Goal option for verify...

if I put "verify.." directly in code, students might edit it (intentionally or not), 
but if it is saved in World Goals (and executed at the end of program) -- this shouldn't happen ;)
 
it would help me with my automatic testing.

**Comment by aroberge** [comment]
If I understand correctly, one way to do this would be to have an option that would open a small editor in which the world-creator would write some code; this code would then be appended at the end of the student code (but not shown to the student) prior to code execution.

**Comment by dz0** [comment]
Yes

And verify could have optional custom message(s) for success/fail :)

**Comment by aroberge** [comment]
Using `try/except` it is possible to get a custom message.

    select_world("Home 1")
    move()
    move()
    try:
        test = 'reeborg.x==3'
        verify(test)
    except ReeborgError as e:
        if e.reeborg_says == "Failed: <br>" + test:
            say("caught!")
            custom_message = "whatever"

**Comment by dz0** [comment]
Maybe there could be "preprocess" and "postprocess" functions/parts?
mithg help with automatic tests https://github.com/aroberge/reeborg/issues/96#issuecomment-102290689

**Comment by aroberge** [comment]
Once I have the end code working, it will be trivial to add the "preprocess" one as well.

**Comment by aroberge** [comment]
![capture](https://cloud.githubusercontent.com/assets/629698/7654066/a0ea43a0-faf0-11e4-8a62-1852ac594c55.PNG)

**Comment by dz0** [comment]
maybe interface should show text areas for pre/post-code: would let editting..
as now one can only create new pre/post-codes...

**Comment by dz0** [comment]
And I'd propose the code to be javascript -- as it could run trigger tests for me ;) 
and wouldn't cause #119

**Comment by aroberge** [comment]
I thought of using textareas but the interface was getting rather cluttery; re-using the editor seemed like a clean way to do things. I do agree that it sometimes would be desirable to edit (or, that the very least, **view**) the code intended to run with a given world.  This would mean though that a student would be able to view the pre- and post- code by clicking on the "edit" button; I am not entirely sure that this is desired.

I disagree about the inserted code being javascript by default; teacher using Reeborg's World may not be familiar enough with Javascript. 

Regarding your automated tests: may I suggest, as a first implementation, that you create a Javascript function that does what you want (and which could be run by using the browser console instead of clicking a button).  For example, if you execute `RUR.ui.run()` in the Javascript console, the program will be run once.  It might very well be that your code would be of interest to other teachers as well, and could be integrated in the code base to be made available from Python as a pre-code instruction for everyone.

**Comment by aroberge** [comment]
@dz0 pre- and post- code now viewable.  Ready for further testing.

**Comment by aroberge** [comment]
Closing this issue now as the original goal has been achieved.
