### ISSUE TITLE
Custom goal msg

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#129]
Custom (optional) msg's could bring in some more fun (joined with custom objects).
There could be msg ir list of msgs for success and another - for failure.
In case of list -- random msg would be shown (like in old good tanks game :) ).

Successs examples:
- you found the treasure
- You successfully escaped
- you saved the world! (if you take a bomb in x moves)

Failure:
- Poor pirate... 
- Where is the exit? You got stuck in the labyrinth...
- Ups, the bomb made BoOM!

There could be separage msg for each goal and one for global task...
They could be input via text area (per line).

**Comment by aroberge** [comment]
I have already started incorporating custom message with custom tiles (not objects).  See https://github.com/aroberge/reeborg/blob/master/src/js/tiles.js

For the rest ... I believe it is already possible, by using some post-code to insert custom messages at the end.

Rather than planning features in the abstract, I would like some specific/concrete world example with specific request to do X given Y in that world.  Then, I could see if it is possible to do it with what is already there - and possibly include such example on the "teaching tricks" page (http://reeborg.ca/teaching_tricks.html).  If it is not possible, then I could look into how to add functionality to make it posssible.    However, this will have to wait until the more "standard" features are put in place.
