### ISSUE TITLE
Blockly "Repeat" command probably should translate to fakePython "repeat"? 

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#285]
At least this would seem more consistent.. 

maybe could add a comment, that "repeat" in py is simplification

**Comment by aroberge** [comment]
Blockly's "repeat" (in English) is "répéter" in French, etc.    It is the name provided by Blockly for indicating a generic "for loop" in various languages.  I would need to modify the Blockly library itself to change it so that it would use something else than a for loop, and it would likely confuse non-English users.

Reeborg's "repeat" is a non-valid Python keyword introduced to simplify the presentation of the concept of loops for beginners that do not use blockly but the editor.

When using Reeborg's keyboard, I indicate that "repeat" is not a true Python keyword.

One solution would be to change the name of Reeborg's "repeat" to something else.
