### ISSUE TITLE
input

### ISSUE THREAD

**Issue by Julian1022438899** [aroberge/reeborg#454]
Realizar las entradas del input con la respectiva ejecución, ya que no es recomendable digitar todos los datos ingresados por el usuario y luego realizar la ejecución.

**Comment by aroberge** [comment]
Disculpe, hablo español solamente un poquito y no entiendo lo que escribe.  Hablo inglés y francés.

**Comment by Julian1022438899** [comment]
Ok, my apologies, 
Make the input of the input with the respective execution, since it is not advisable to type all the data entered by the user and then perform the execution.

**Comment by aroberge** [comment]
I don't understand what you are talking about.

What do you mean by "to type all the data entered by the user?"  Who
exactly, other than the user, is typing anything in Reeborg's World?  Are
you sure you are commenting about http://reeborg.ca/reeborg.html ?

**Comment by Julian1022438899** [comment]
What I mean is that the data that is typed in the command window of the world of Reeborg must be evaluated and executed instantly, the problem is that I can type one data and then others and Reeborg what it does is run after typing All the data that I have requested.
thanks

**Comment by aroberge** [comment]
You can type the entire program in the editor, and then run it using the
button
[image: image.png]

Or, you can choose a different mode [REPL (py)], entering one command at a
time and see the result of the execution of that command.
[image: image.png]

**Comment by aroberge** [comment]
If you are talking about using Python's "input()" function ... that is not
supported.  In Python, input() suspends the execution, waiting for the user
to type in something.  In effect, the program "sleeps" while waiting for
the user to type in something.

In this web version, all Python code is translated into Javascript prior to
execution. Javascript does not support a "sleep" function - it cannot
suspend its execution.

(There is a python-like version called Skulpt which does support input(),
but it is not fully compatible with Python 3 which is why I did not use it.)

**Comment by aroberge** [comment]
Closing as lacking information to be able to do any meaningful followup.
