### ISSUE TITLE
Custom objects (and their images)

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#86]
Custom objects with teir images could be added in objects edit menu and saved in permalink.
Images could be as links or as SVG.

It would let to make more creative/fun tasks :)

ps.: custom img can also be applied to robot and background.

**Comment by aroberge** [comment]
Superficially a good idea, and my first reaction was very positive.  However, stepping back, I am not sure I see the use case: having specific use cases would determine how to implement it.

For example, having custom robots seems like a nice idea; I was asked for this by a teacher who was using rur-ple (the desktop precursor of Reeborg's World) and I implemented it .... and, to my knowledge, no one has ever used it.   To use it, you need to supplement 4 images, one for each orientations.   I could make do with a single image (rotating it based on the orientation), but the code would be a bit more complicated than the existing one.

I'll keep this as a possible enhancement ... waiting for specific use cases/examples before I think of how to implemenent it.

**Comment by dz0** [comment]
ps.: SVG code could be included in Permalink

**Comment by dz0** [comment]
Application ideas:
- there could be "mushroom" objects (edible and nonedible), and Reeborg should pick-up good ones :)
- Bee could gather honey/flowers, like in http://studio.code.org/s/course1/stage/7/puzzle/3

ps.: pictures could make Reeborg more appealing to girls -- there is trend to try attract them to IT ;)

pps.: not high priority

**Comment by aroberge** [comment]
Including the SVG code in a permalink would run the risk of exceeding the maximum length of URLs handled by browsers; even though Google Chrome is supposed to have a very long limit, I hit some sort of limit with a long program pasted in the url bar which is what lead me to the "update the textarea" approach.

Initially, I wanted this version of Reeborg to be extremely "rich" in terms of images supported, etc. Rather than geometric shape, I had been thinking of drawing "nice" pictures ... but quickly found out that my artistic skills were very inadequate.  So, I settled for simple shapes.

I would definitely be more than willing ot add more objects supported in the world, including background pictures.   If you have images that you would like to use, and possibly additional tests (e.g. `is_edible()`, to use the mushroom example) or other instructions, I would be happy to incorporate them in Reeborg's world.

**Comment by dz0** [comment]
https://openclipart.org/ has lots of nice public domain pics :)
and linking to them is probably safe in longterm..

They are SVG, but can export to png (can controll the size via url):
https://openclipart.org/image/25px/svg_to_png/183893/simple-apple.png

On Wed, May 13, 2015 at 2:28 PM, André Roberge <notifications@github.com>
wrote:

> Including the SVG code in a permalink would run the risk of exceeding the
> maximum length of URLs handled by browsers; even though Google Chrome is
> supposed to have a very long limit, I hit some sort of limit with a long
> program pasted in the url bar which is what lead me to the "update the
> textarea" approach.
>
> Initially, I wanted this version of Reeborg to be extremely "rich" in
> terms of images supported, etc. Rather than geometric shape, I had been
> thinking of drawing "nice" pictures ... but quickly found out that my
> artistic skills were very inadequate. So, I settled for simple shapes.
>
> I would definitely be more than willing ot add more objects supported in
> the world, including background pictures. If you have images that you would
> like to use, and possibly additional tests (e.g. is_edible(), to use the
> mushroom example) or other instructions, I would be happy to incorporate
> them in Reeborg's world.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aroberge/reeborg/issues/86#issuecomment-101632875>.
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by aroberge** [comment]
@dz0 @goldsong I'm thinking of adding objects that are too heavy for Reeborg to pick up, but that it could push around ... so that sokoban type puzzles could be created.  As Reeborg would `move()`, it would push up such objects ... provided there is no obstacle behind.

Just a thought...

**Comment by dz0** [comment]
Ok, so objects should have some kind of callbacks to move or on_robot?

I'd also like to have automatically asinchronically moving objects, like
enemies in CodeCombat.com
These objects should have setTimeOut callback which could be defined in
world or library? Or  could we use Robot base class for objects that move
...?

**Comment by aroberge** [comment]
Objects that could move aynchronously could not be accommodated within Reeborg's world paradigm: the focus is on giving the user the choice of "setting the pace", allowing to pause a program (and even step back to see what happened at a previous step - see the additional menu).  To be more explicit: a program is run, "frames" are recorded, which can then be played back, either step by step, or all at once, or occasionally paused, sped up for a while (using the `think()` command) etc.   I don't see how to accommodate independently moving objects in such a scenario.

CodeCombat.com has a completely different philosophy.  Once you run the program, you watch it at a predefined speed (something on which you have no control).  The two approaches are incompatible.   

With a desktop application, it might be possible to combine these approaches, as one can pause execution of a Python program, and have multiple threads.  This is not possible with Javascript, and this is why I chose the "run, record frames, playback and watch/pause" approach.  CodeCombat is using a simple "run and watch" approach.

**Comment by dz0** [comment]
Ok, I understand.

Then it could be synchronized in a way, that each robot move could trigger
next move (position change) of "enemy" (positions should be queued).

Random enemy position (from a list) for each robot move could also be
enough for many CodeCombat like tasks.

**Comment by aroberge** [comment]
I still don't know how it would be possible to have independently moving "entities" with the current code I use.   However, this is something that could be perhaps looked at, once I have changed the code to incorporate various types of objects and tiles.

**Comment by dz0** [comment]
This movement of objects is low priority, but though would be attractive to
kids :-)

But maybe triggering object "(dis)appear" (in random or exact place)  when
robot is on some specific cell would make tasks more game like...

**Comment by dz0** [comment]
The trigger could be more general - like "goal" or "vetify" based.

On another thought, this is also low priority... And might be too
distracting :-)

**Comment by Goldsong** [comment]
this is a nice idea.  I wondering whether there is too much in the plate already, though. But I can see this kind of object being useful to add variety to the missions as long as no new comand is added. Thus, for example, the robot might move against a grandfather’s clock tile and they will move together, robot and clock, until the clock has a wall behind, at which time a move against the clock will cause a crash. I’ll comment on issue #100


> On May 23, 2015, at 5:39 AM, André Roberge <notifications@github.com> wrote:
> 
> @dz0 <https://github.com/dz0> @goldsong <https://github.com/goldsong> I'm thinking of adding objects that are too heavy for Reeborg to pick up, but that it could push around ... so that sokoban type puzzles could be created. As Reeborg would move(), it would push up such objects ... provided there is no obstacle behind.
> 
> Just a thought...
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/aroberge/reeborg/issues/86#issuecomment-104888954>.
> 

All the best,

Andres

**Comment by Goldsong** [comment]
> On May 23, 2015, at 6:20 AM, André Roberge <notifications@github.com> wrote:
> 
> Objects that could move aynchronously could not be accommodated within Reeborg's world paradigm: the focus is on giving the user the choice of "setting the pace", allowing to pause a program (and even step back to see what happened at a previous step - see the additional menu). To be more explicit: a program is run, "frames" are recorded, which can then be played back, either step by step, or all at once, or occasionally paused, sped up for a while (using the think() command) etc. I don't see how to accommodate independently moving objects in such a scenario.
> 
> CodeCombat.com has a completely different philosophy. Once you run the program, you watch it at a predefined speed (something on which you have no control). The two approaches are incompatible.
> 
> With a desktop application, it might be possible to combine these approaches, as one can pause execution of a Python program, and have multiple threads. This is not possible with Javascript, and this is why I chose the "run, record frames, playback and watch/pause" approach. CodeCombat is using a simple "run and watch" approach.
> 
I have used other programs that run at a predefined speed and it becomes a nightmare to debug the final steps of long missions, e.g., say a maze, because you end up sitting a full minute or more, watching the screen, waiting for the robot to get to the end, where the debugging needs to take place.

**Comment by aroberge** [comment]
Regarding adjustable speed and debugging of long missions: this is indeed one of the reasons I included the adjustable speed.  I consider it an essential part of Reeborg's World.

**Comment by aroberge** [comment]
I have started to add custom images for objects (and change the back end code).  As I am writing this, "star" and "triangle" have been done (some code still to be removed). **Note: this is for drawing only.** Existing worlds that used "star" would likely not work anymore (and soon it will be the same for "triangle").   

Goals are indicated by a monochrome version of the image.

Currently, I use tiles with size 40x40 pixels; I found it more reliable to use the same size image (with transparent background) for the images as well: it makes the positioning the same for all types of object. Of course, the images themselves are smaller than this, so that they fit "nicely".

After playing with some images that @Goldsong sent me, I decided to use instead some from openclipart as starting point.   For the triangle, I could not find a standard one that was suitable, so I decided to go with a colourful "impossible triangle" instead; perhaps young students will find this interesting.

I need to work at the code for `take()` and `put()`.  Right now, I have a lot of unresolved questions as to what to do.

**First, ignoring tokens and considering only other objects:**

1. should I allow more than one object of a given type at a given location? Currently this is not allowed, but it would likely be a good addition i.e. I am thinking of doing this.  (this will mean modification to the world editor as well)
2. If I have more than one object of a given type at a given location, should I indicate the number?  I am thinking of doing it, if the number is greater than 1.  The same would be the case for a "goal".
3. Should I allow multiple type of objects at a given location (e.g. strawberry and weeds)? I am thinking that the answer should be yes.  The same would be the case for a "goal"; it would be up to a world designer to avoid making something too messy...
4. If I have more than one object type at a given location, should I indicate some number?  I am thinking that, perhaps, the **total** number of objects at a given location, regarless of type, should be indicated.  The same would be the case for a "goal".
5. Should I allow for a range of a number of number of objects (exact number chosen randomly at the beginning of each run) at a given location, like is done for tokens.  Again, I think this should be allowed.  It would be up to a world designer to avoid making something too messy looking.
6. If only object of one type are found at a given location (or carried by Reeborg), should we need to type an argument for `put()` or `take()`?   Currently, this is the case.  However, I think I have been convinced by at least one of you to change this behaviour: if only one type of object is found at a given location, `take()` would not require an argument to specify the type of object.  If Reeborg carries more than one type of objects (**including tokens**), then `put()` would require an argument specifying the type of object **including tokens** (this last would be a change, done for consistency).
7. Should I allow for a range of values for the number of objects as a **goal** at a given location?  I am **very strongly** against this idea: right now, to see if a goal has been satisfied in terms of number of objects put on various position in the world, I use a function that compares equality between javascript objects (partial world state, taking only objects into account, and corresponding goal specified in JSON notation and then converted into a Javascript object).  It is a relatively full proof method, not prone to bugs and would not work if  a range of number of objects is specified as a goal.  I think that there is enough flexibility as it is to create interesting challenges.  Note that the final position of the robot can be specified as "one of many" ... and I'm not even sure of the value of that.  
8. Should I keep having multiple potential final position for the robot (selected randomly)?   I'm thinking of removing this as I think it adds very little value, and is not consistent with other "goals".

Now, about tokens ....  When a plain world is used, I like the simplicity of the tokens drawn as they are.  Perhaps they should be kept as they are (and their number, including 1, always be indicated, unlike my suggestion above for other objects).

**Comment by aroberge** [comment]
As a first step in dealing with the new generic objects, the original behaviour of `put` and `take` has been "restored" with the new objects.  

http://reeborg.ca/world_dev.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A%22infinite%22%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%7D%5D%2C%22walls%22%3A%7B%7D%2C%22tokens%22%3A%7B%222%2C1%22%3A1%7D%2C%22objects%22%3A%7B%223%2C1%22%3A%22star%22%2C%224%2C1%22%3A%22triangle%22%2C%225%2C1%22%3A%22square%22%7D%2C%22goal%22%3A%7B%22tokens%22%3A%7B%226%2C1%22%3A1%7D%2C%22objects%22%3A%7B%227%2C1%22%3A%22star%22%2C%228%2C1%22%3A%22triangle%22%2C%229%2C1%22%3A%22square%22%7D%7D%7D&editor=move()%0Atake()%0Amove()%0Atake(%22star%22)%0Amove()%0Atake(%22triangle%22)%0Amove()%0Atake(%22square%22)%0Afor%20item%20in%20%5B'token'%2C%20'star'%2C%20'triangle'%2C%20'square'%5D%3A%0A%20%20%20%20move()%0A%20%20%20%20put(item)%0A%0A%0A&library=%23%20'from%20my_lib%20import%20*'%20in%20Python%20Code%20is%20required%20to%20use%0A%23%20the%20code%20in%20this%20library.%20%0A%0A

**Comment by dz0** [comment]
On May 24, 2015 5:21 PM, "André Roberge" <notifications@github.com> wrote:

>
> I need to work at the code for take() and put(). Right now, I have a lot
> of unresolved questions as to what to do.
>
> *First, ignoring tokens and considering only other objects:*
>
>    1. should I allow more than one object of a given type at a given
>    location? Currently this is not allowed, but it would likely be a good
>    addition i.e. I am thinking of doing this. (this will mean modification to
>    the world editor as well)
>
> ok

>
>    1. If I have more than one object of a given type at a given location,
>    should I indicate the number? I am thinking of doing it, if the number is
>    greater than 1. The same would be the case for a "goal".
>
> ok

>
>    1. Should I allow multiple type of objects at a given location (e.g.
>    strawberry and weeds)? I am thinking that the answer should be yes. The
>    same would be the case for a "goal"; it would be up to a world designer to
>    avoid making something too messy...
>
> maybe for further future version?
is it ok, that one object would cover other?

>
>    1. If I have more than one object type at a given location, should I
>    indicate some number? I am thinking that, perhaps, the *total* number
>    of objects at a given location, regarless of type, should be indicated. The
>    same would be the case for a "goal".
>
> or 3+2+2 style

>
>    1. Should I allow for a range of a number of number of objects (exact
>    number chosen randomly at the beginning of each run) at a given location,
>    like is done for tokens. Again, I think this should be allowed. It would be
>    up to a world designer to avoid making something too messy looking.
>
> yes
proposal: clicking LeftMouse would put/hide one object, but Shift+Click or
RightClick would bring up quantity dialog.

>
>    1. If only object of one type are found at a given location (or
>    carried by Reeborg), should we need to type an argument for put() or
>    take()? Currently, this is the case. However, I think I have been
>    convinced by at least one of you to change this behaviour: if only one type
>    of object is found at a given location, take() would not require an
>    argument to specify the type of object. If Reeborg carries more than one
>    type of objects (*including tokens*), then put() would require an
>    argument specifying the type of object *including tokens* (this last
>    would be a change, done for consistency).
>
> ok

>
>    1. Should I allow for a range of values for the number of objects as a
>    *goal* at a given location? I am *very strongly* against this idea:
>    right now, to see if a goal has been satisfied in terms of number of
>    objects put on various position in the world, I use a function that
>    compares equality between javascript objects (partial world state, taking
>    only objects into account, and corresponding goal specified in JSON
>    notation and then converted into a Javascript object). It is a relatively
>    full proof method, not prone to bugs and would not work if a range of
>    number of objects is specified as a goal. I think that there is enough
>    flexibility as it is to create interesting challenges. Note that the final
>    position of the robot can be specified as "one of many" ... and I'm not
>    even sure of the value of that.
>
>
>    1. Should I keep having multiple potential final position for the
>    robot (selected randomly)? I'm thinking of removing this as I think it adds
>    very little value, and is not consistent with other "goals".
>
> Probably no big need for randomized goals...

But I'd like some "parametrized goals" -- for example -- final position
depends on number of tokens found (randomized at start).  Now I suppose to
use verify in postcode for that.

> Now, about tokens .... When a plain world is used, I like the simplicity
> of the tokens drawn as they are. Perhaps they should be kept as they are
> (and their number, including 1, always be indicated, unlike my suggestion
> above for other objects).
>
ok (but other way is ok too :)

**Comment by aroberge** [comment]
On Sun, May 24, 2015 at 9:20 PM, dz0 <notifications@github.com> wrote:

> On May 24, 2015 5:21 PM, "André Roberge" <notifications@github.com> wrote:
>
> >
> > 1. Should I allow multiple type of objects at a given location (e.g.
> > strawberry and weeds)? I am thinking that the answer should be yes. The
> > same would be the case for a "goal"; it would be up to a world designer
> to
> > avoid making something too messy...
> >
> > maybe for further future version?
> is it ok, that one object would cover other?
>

yes, I believe so


>
> >
> > 1. If I have more than one object type at a given location, should I
> > indicate some number? I am thinking that, perhaps, the *total* number
> > of objects at a given location, regarless of type, should be indicated.
> The
> > same would be the case for a "goal".
> >
> > or 3+2+2 style
>
>
The problem is to find the space to write the information in the space
given.
I prefer the idea of being able to click on the world to get more
information.



> >
> > 1. Should I allow for a range of a number of number of objects (exact
> > number chosen randomly at the beginning of each run) at a given location,
> > like is done for tokens. Again, I think this should be allowed. It would
> be
> > up to a world designer to avoid making something too messy looking.
> >
> > yes
> proposal: clicking LeftMouse would put/hide one object, but Shift+Click or
> RightClick would bring up quantity dialog.
>

yes - as noted in a separate issue and referred to above.

>
> >
> > 1. Should I keep having multiple potential final position for the
> > robot (selected randomly)? I'm thinking of removing this as I think it
> adds
> > very little value, and is not consistent with other "goals".
> >
> > Probably no big need for randomized goals...
>
> But I'd like some "parametrized goals" -- for example -- final position
> depends on number of tokens found (randomized at start). Now I suppose to
> use verify in postcode for that.
>
>
There is no way that I can do this in a fully reliable way - so I prefer to
leave
it under programmer's control as it currently is.

**Comment by aroberge** [comment]
Regarding parametrized goals: I will implement a goal feature where **all** the objects of a given type will be required to be dropped at the same location.  When initial conditions are chosen, the total number of objects of a give type is calculated and replace the "all" value for the corresponding goal.  This will work for each type of object in a given world.
