### ISSUE TITLE
print result is ahead of Reeborg actions

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#88]
I tried
```py
for x in range(5):
    move()
    print(x)
```

with "Step:
and I can instantly see all output in diary before Reeborg moves.

It probably needs to "save" current output in each step (as it does with Reeborg state).

**Comment by dz0** [comment]
I guess people seldom use print in this tool, "say(..)" is good workaround in this case... :)

**Comment by aroberge** [comment]
The way a program is designed, it is run in its entirety and each step is saved as a "frame" which can then be played back, usually forward (but it's possibly to step backward from a given point - see the additional menu at the top).   As a result, all print() outputs are shown before Reeborg moves (and the frame playback begins).  However, there is another command, write(), which can be used instead of print().

**Comment by aroberge** [comment]
I found a way to implement print() so that it records the same way that write() does, i.e. per frame.  See issue 90 (which notes that the tutorials need to be updated.)
